export enum ROUTE_NAME {
  HOME = 'HOME',
  AUTH_LOGIN = 'AUTH.LOGIN',
  AUTH_REGISTER = 'AUTH.REGISTER',
  ABOUT = 'ABOUT',
  PROFILE = 'PROFILE',
  // Shop
  SHOP_CART = 'SHOP.CART',
  SHOP_CATEGORY = 'SHOP.CATEGORY',
  SHOP_CHECKOUT = 'SHOP.CHECKOUT',
  SHOP_OFFER = 'SHOP.OFFER',
  SHOP_ORDER = 'SHOP.ORDER',
  SHOP_ORDERS = 'SHOP.ORDERS',
  SHOP_SEARCH = 'SHOP.SEARCH',
  SHOP_STORE = 'SHOP.STORE',
  SHOP_STORES = 'SHOP.STORES',
}
