export enum ROUTE_NAME {
  HOME = 'HOME',
  AUTH_LOGIN = 'AUTH.LOGIN',
  AUTH_REGISTER = 'AUTH.REGISTER',
  // Shop
  SHOP_OFFER = 'SHOP.OFFER',
  SHOP_STORE = 'SHOP.STORE',
  SHOP_STORES = 'SHOP.STORES',
}
